Repository Bookingjini-Labs/bookingjini-icons, pull requests merged in 2023-06, with the labels that each got.

#218 Added hover effect on text
  website/index.html
  website/style-dark.css
  website/style.css
Labels: GSSoC23, Level 3

#220 "Enhancement: Replace 'Get CDN' Button with 'Star Repo' Button and Open in New Page"
  website/index.html
  website/style-dark.css
  website/style.css
Labels: GSSoC23, Level 2

#253 Enhanced hover text
  website/style-dark.css
Labels: GSSoC23, Level 1

#248 3 types of icons
  .gitignore
  icons.zip
Labels: GSSoC23, Level 3

#290 💡 [FEAT]: MADE SOCIAL ANCHORS ACCESSIBLE ON FOOTER
  website/index.html
Labels: GSSoC23, Level 1

#312 Added main link to logo
  website/index.html
  website/responsive.css
  website/style-dark.css
  website/style.css
Labels: gssoc23, level1

#319 heading colour changed for dark and light theme
  website/style-dark.css
  website/style.css
Labels: gssoc23, level1

#339 [FEAT]: IMPROVING SEO SCORE BY ADDING IMPORTANT META ELEMENTS 🚀
  website/index.html
Labels: gssoc23, level3
