Repository Bookingjini-Labs/bookingjini-icons, pull requests merged in 2023-05, with the labels that each got.

#29 Added the favicon and closed Issue #28
  assets/77221742.ico
  website/index.html
Labels: good first issue, GSSoC23

#39 contribution flow added to documentation
  README.md
Labels: documentation, good first issue, GSSoC23

#44 Update README.md
  README.md
Labels: documentation, good first issue, GSSoC23

#52 Added Scroll-to-Top button
  fonts/font-css.css
  website/index.html
  website/scrollToTop.js
  website/style-dark.css
  website/style.css
Labels: good first issue, GSSoC23, Level 3

#100 Website's Updated Font
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  website/index.html
  website/style-dark.css
Labels: GSSoC23

#102 Added CODE_OF_CONDUCT file
  .github/reminder.yml
  .github/workflows/main.yml
  CODE_OF_CONDUCT.md
  website/index.html
  website/style-dark.css
Labels: documentation, GSSoC23, Level 1

#67 Update README.md
  README.md
Labels: GSSoC23, Level 1

#118 Fix issue reponsive #95
  website/index.html
  website/style-dark.css
  website/style.css
Labels: GSSoC23

#181 Update style.css for Light/Dark mode toggle button #157
  website/style.css
Labels: GSSoC23, Level 2

#180 Update style-dark.css for Dark/Light mode button #157
  website/style-dark.css
Labels: GSSoC23, Level 2

#179 Update Dark/Light Mode button #157
  website/index.html
Labels: GSSoC23, Level 2

#173 Added Feature - No Result Found
  website/index.html
  website/style-dark.css
  website/style.css
Labels: GSSoC23, Level 2

#172 #134 "Added Search Icon to search Bar"
  website/index.html
  website/style-dark.css
  website/style.css
Labels: GSSoC23, Level 2

#161 Implemented fuzzy search #135
  website/index.html
  website/searchIcons.js
Labels: GSSoC23, Level 2

#186 Added Mockups to search bar
  website/index.html
  website/style-dark.css
  website/style.css
Labels: GSSoC23, Level 2

#188 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: GSSoC23, Level 3
