Repository Bookingjini-Labs/bookingjini-icons, pull requests merged in 2023-07, with the labels that each got.

#365 fix: bug on browser's console
  website/script.js
Labels: gssoc23, level1

#367 search box performance improved and bug solved
  website/script.js
  website/searchIcons.js
Labels: gssoc23, level2

#369 solves redirection
  website/error404.html
Labels: gssoc23, level1

#364 Icon changes on copying the code
  website/script.js
Labels: gssoc23, level1

#384 Made the navbar brand logo responsive
  website/index.html
  website/responsive.css
  website/style-dark.css
  website/style.css
Labels: gssoc23, level1

#402 Fix logo in react icons `README.md`
  package/README.md
  package/assets/logo.png
Labels: gssoc23, level1

#411 modeselection
  website/contributors.html
  website/index.html
Labels: gssoc23, level1

#430 docs: improve issue forms and add checklist
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc23, level2

#431 feat: show star stats of the repository in the star CTA
  website/contributors.html
  website/index.html
  website/script.js
Labels: gssoc23, level2

#429 docs: fix indendation issue and add checklist
  .github/ISSUE_TEMPLATE/documentation_issue.yml
Labels: gssoc23, level1

#441 Contribution
  website/contributor.js
  website/contributors.css
  website/style.css
Labels: gssoc23, level2

#440 Create README.md
  New-Website-Design/README.md
Labels: gssoc23, level3

#443 updated transition
  website/style.css
Labels: gssoc23, level1
